require 'Items/SuburbsDistributions'
require 'Items/Distributions'
table.insert(SuburbsDistributions,bowling);
SuburbsDistributions["bowling"] = {
    shelves ={
        rolls = 5,
        items = { 
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
        }		
	},
    locker ={
        rolls = 5,
        items = { 
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
        }		
	},
};
table.insert(SuburbsDistributions,bowling2);
SuburbsDistributions["bowling2"] = {
    shelves ={
        rolls = 5,
        items = {
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
        }		
	},
    locker ={
        rolls = 5,
        items = { 
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
			"Base.Bowlingball", 15,
        }		
	},
};
table.insert(SuburbsDistributions,bowlingstorage);
SuburbsDistributions["bowlingstorage"] = {
    crate ={
        rolls = 5,
        items = {
			"Base.Bowlingball", 15,
			"Base.Bowlingball", 15,
			"Base.Bowlingball", 15,
			"Base.Bowlingball", 15,
			"Base.BowlingPin", 15,
			"Base.BowlingPin", 10,
			"Base.BowlingPin", 5,
			"Base.BowlingPin", 2,
        }
	},
    locker ={
        rolls = 5,
        items = {
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainers", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersRed", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
			"Base.Shoes_BowlingTrainersGreen", 15,
        }
	},
};
table.insert(SuburbsDistributions,bowlingclothes);
SuburbsDistributions["bowlingclothes"] = {
    crate ={
        rolls = 5,
        items = { 
        }
	},
};
table.insert(SuburbsDistributions,fishingstorestorage);
SuburbsDistributions["fishingstorestorage"] = {
    shelves ={
        rolls = 5,
        items = {
            "Base.BookFishing1", 2,
            "Base.BookFishing2", 1,
            "Base.BookFishing3", 0.8,
            "Base.BookFishing4", 0.6,
            "Base.BookFishing5", 0.2,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
        }
    },
    crate ={
        rolls = 5,
        items = {
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
        }
    },
    counter ={
        rolls = 5,
        items = {
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
        }
    },
};
table.insert(SuburbsDistributions,huntingstore);
SuburbsDistributions["huntingstore"] = {
    displaycase ={
        rolls = 3,
        items = {
            "TrapMouse", 2,
			"HuntingRifle", 2,
			"VarmintRifle", 2,
			"Shotgun", 2,
			"DoubleBarrelShotgun", 3,
			"ShotgunShellsBox", 5,
			"223Box", 5,
			"308Box", 5,
			"ShotgunShellsBox", 5,
			"223Box", 5,
			"308Box", 5,
			"Vest_Hunting_Grey", 2,
			"Vest_Hunting_Orange", 2,
			"Vest_Hunting_Camo", 2,
			"Vest_Hunting_CamoGreen", 2,
        }
    },
    shelves ={
        rolls = 3,
        items = {
            "GunPowder", 1,
			"223Box", 5,
			"308Box", 5,
			"223Box", 5,
			"308Box", 5,
			"223Box", 5,
			"308Box", 5,
			"ShotgunShellsBox", 5,
			"ShotgunShellsBox", 5,
			"ShotgunShellsBox", 5,
			"BookTrapping1", 4,
			"BookTrapping2", 3,
			"BookTrapping3", 2,
			"BookTrapping4", 1.4,
			"BookTrapping5", 0.6,
        }
    },
	cashregister = {
		rolls = 5,
		items = {
			"Money", 2,
			"Money", 100,
			"Money", 100,
		},
	},
};

table.insert(SuburbsDistributions,displayfishingstore);
SuburbsDistributions["displayfishingstore"] = {
    displaycase ={
        rolls = 5,
        items = {
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
        }
    },
};

table.insert(SuburbsDistributions,fishingstore);
SuburbsDistributions["fishingstore"] = {
    displaycase ={
        rolls = 3,
        items = {
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
        }
    },
    shelves ={
        rolls = 3,
        items = {
            "Base.BookFishing1", 1,
            "Base.BookFishing2", 0.5,
            "Base.BookFishing3", 0.4,
            "Base.BookFishing4", 0.3,
            "Base.BookFishing5", 0.1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
            "Base.FishingRod", 4,
            "Base.FishingNet", 2,
            "Base.FishingLine", 1,
			"Base.PaperclipBox", 0.5,
        }
    },
    shelvesmag ={
        rolls = 3,
        items = {
            "Base.FishingMag1", 1,
            "Base.FishingMag2", 1,
            "Base.FishingMag1", 0.5,
            "Base.FishingMag2", 0.5,
            "Base.FishingMag1", 0.5,
            "Base.FishingMag2", 0.5,
        }
    },
	cashregister = {
		rolls = 3,
		items = {
			"Money", 2,
			"Money", 100,
			"Money", 100,
		},
	},
};
table.insert(SuburbsDistributions,riversidegunstore);
SuburbsDistributions["riversidegunstore"] = {
	counter ={
		rolls = 3,
		items = {
			"9mmClip", 1.5,
			"45Clip", 1.5,
			"44Clip", 1.5,
			"308Clip", 1.5,
			"x2Scope", 3,
			"x4Scope", 2,
			"x8Scope", 1,
            "AmmoStrap_Bullets", 3,
            "AmmoStrap_Shells", 3,
			"Sling", 4,
			"FiberglassStock", 3,
			"RecoilPad",  4,
			"HuntingRifle", 3,
			"VarmintRifle", 3,
			"Shotgun", 3,
			"DoubleBarrelShotgun", 2,
			"ShotgunShellsBox", 10,
			"ShotgunShellsBox", 10,
			"Pistol", 1.5,
			"Pistol2", 1.5,
			"Pistol3", 0.5,
			"Revolver_Short", 1.5,
			"Revolver", 1,
			"Revolver_Long", 0.5,
			"HuntingKnife", 5,
			"Bullets9mmBox", 10,
			"Bullets9mmBox", 10,
			"GunPowder", 10,
			"GunPowder", 10,
			"GunPowder", 10,
			"223Box", 10,
			"308Box", 10,
			"223Box", 10,
			"308Box", 10,
			"Bullets38Box", 10,
			"Bullets44Box", 10,
			"Bullets45Box", 10,
			"Bullets38Box", 10,
			"Bullets44Box", 10,
			"Bullets45Box", 10,
			"Axe", 2,
			"WoodAxe", 3,
			"HuntingKnife", 3,
			"HuntingMag1", 0.2,
			"HuntingMag2", 0.2,
			"HuntingMag3", 0.2,
			"Radio.WalkieTalkie4",10,
			"Radio.WalkieTalkie5",5,
			"Radio.HamRadio1",10,
			"Radio.HamRadio2",5,
			"Glasses_Shooting", 2,
		},
		dontSpawnAmmo = true,
	},

	displaycase ={
		rolls = 3,
		items = {
			"9mmClip", 1.5,
			"45Clip", 1.5,
			"44Clip", 1.5,
			"308Clip", 1.5,
			"x2Scope", 3,
			"x4Scope", 2,
			"x8Scope", 1,
            "AmmoStrap_Bullets", 3,
            "AmmoStrap_Shells", 3,
			"Sling", 4,
			"FiberglassStock", 3,
			"RecoilPad",  4,
			"HuntingRifle", 3,
			"VarmintRifle", 3,
			"Shotgun", 3,
			"DoubleBarrelShotgun", 2,
			"ShotgunShellsBox", 10,
			"ShotgunShellsBox", 10,
			"Pistol", 1.5,
			"Pistol2", 1.5,
			"Pistol3", 0.5,
			"Revolver_Short", 1.5,
			"Revolver", 1,
			"Revolver_Long", 0.5,
			"HuntingKnife", 5,
			"Bullets9mmBox", 10,
			"Bullets9mmBox", 10,
			"Bullets38Box", 10,
			"Bullets44Box", 10,
			"Bullets45Box", 10,
			"Bullets38Box", 10,
			"Bullets44Box", 10,
			"Bullets45Box", 10,
			"GunPowder", 10,
			"GunPowder", 10,
			"223Box", 10,
			"308Box", 10,
			"223Box", 10,
			"308Box", 10,
			"Axe", 3,
			"Glasses_Shooting", 2,
		},
		dontSpawnAmmo = true,
	},

	locker ={
		rolls = 3,
		items = {
			"9mmClip", 1.5,
			"45Clip", 1.5,
			"44Clip", 1.5,
			"308Clip", 1.5,
			"x2Scope", 3,
			"x4Scope", 2,
			"x8Scope", 1,
            "AmmoStrap_Bullets", 3,
            "AmmoStrap_Shells", 3,
			"Sling", 4,
			"FiberglassStock", 3,
			"RecoilPad",  4,
			"HuntingRifle", 3,
			"VarmintRifle", 3,
			"Shotgun", 3,
			"DoubleBarrelShotgun", 2,
			"ShotgunShellsBox", 10,
			"ShotgunShellsBox", 10,
			"Pistol", 1.5,
			"Pistol2", 1.5,
			"Pistol3", 0.5,
			"Revolver_Short", 1.5,
			"Revolver", 1,
			"Revolver_Long", 0.5,
			"HuntingKnife", 5,
			"Bullets9mmBox", 10,
			"Bullets9mmBox", 10,
			"GunPowder", 10,
			"GunPowder", 10,
			"223Box", 10,
			"308Box", 10,
			"223Box", 10,
			"308Box", 10,
			"Bullets38Box", 10,
			"Bullets44Box", 10,
			"Bullets45Box", 10,
			"Axe", 2,
			"WoodAxe", 2,
			"Machete", 1,
			"Katana", 0.5,
			"Radio.WalkieTalkie4",5,
			"Radio.WalkieTalkie5",3,
			"Radio.HamRadio1",5,
			"Radio.HamRadio2",3,
			"Glasses_Shooting", 2,
			"Vest_Hunting_Grey", 1,
			"Vest_Hunting_Orange", 1,
			"Vest_Hunting_Camo", 1,
			"Vest_Hunting_CamoGreen", 1,
		},
		dontSpawnAmmo = true,
	},

	metal_shelves ={
		rolls = 3,
		items = {
			"9mmClip", 1.5,
			"45Clip", 1.5,
			"44Clip", 1.5,
			"308Clip", 1.5,
			"HuntingRifle", 3,
			"VarmintRifle", 3,
			"Shotgun", 3,
			"DoubleBarrelShotgun", 2,
			"ShotgunShellsBox", 10,
			"ShotgunShellsBox", 10,
			"Pistol", 1.5,
			"Pistol2", 1.5,
			"Pistol3", 0.5,
			"Revolver_Short", 1.5,
			"Revolver", 1,
			"Revolver_Long", 0.5,
			"HuntingKnife", 3,
			"Bullets9mmBox", 10,
			"Bullets9mmBox", 10,
			"GunPowder", 10,
			"GunPowder", 10,
			"223Box", 10,
			"308Box", 10,
			"Bullets38Box", 10,
			"Bullets44Box", 10,
			"Bullets45Box", 10,
			"Axe", 3,
			"Katana", 0.5,
			"Machete", 1,
			"Radio.WalkieTalkie4",5,
			"Radio.WalkieTalkie5",3,
			"Radio.HamRadio1",5,
			"Radio.HamRadio2",3,
			"Glasses_Shooting", 2,
		},
		dontSpawnAmmo = true,
	},
};

table.insert(SuburbsDistributions,riversidegunstorestorage);
SuburbsDistributions["riversidegunstorestorage"] = {
	all={
		rolls = 3,
		items = {
			"9mmClip", 1.5,
			"45Clip", 1.5,
			"44Clip", 1.5,
			"308Clip", 1.5,
			"x2Scope", 3,
			"x4Scope", 2,
			"x8Scope", 1,
            "AmmoStrap_Bullets", 3,
            "AmmoStrap_Shells", 3,
			"Sling", 4,
			"FiberglassStock", 3,
			"RecoilPad",  4,
			"HuntingRifle", 3,
			"VarmintRifle", 3,
			"Shotgun", 3,
			"DoubleBarrelShotgun", 2,
			"ShotgunShellsBox", 10,
			"ShotgunShellsBox", 10,
			"Pistol", 1.5,
			"Pistol2", 1.5,
			"Pistol3", 0.5,
			"Revolver_Short", 1.5,
			"Revolver", 1,
			"Revolver_Long", 0.5,
			"Bullets9mmBox", 10,
			"Bullets9mmBox", 10,
			"GunPowder", 10,
			"GunPowder", 10,
			"223Box", 10,
			"308Box", 10,
			"223Box", 10,
			"308Box", 10,
			"Bullets38Box", 10,
			"Bullets44Box", 10,
			"Bullets45Box", 10,
			"Axe", 2,
			"WoodAxe", 2,
			"Katana", 0.5,
			"Machete", 1,
			"Radio.WalkieTalkie4",5,
			"Radio.WalkieTalkie5",3,
			"Radio.HamRadio1",5,
			"Radio.HamRadio2",3,
		},

		dontSpawnAmmo = true,
	},
};

table.insert(SuburbsDistributions,riversidepolicestorage);
SuburbsDistributions["riversidepolicestorage"] = {
	locker ={
		rolls = 4,
		items = {
			"9mmClip", 1.5,
			"45Clip", 1.5,
			"44Clip", 1.5,
			"308Clip", 1.5,
			"Nightstick", 4,
			"Shotgun", 3,
			"DoubleBarrelShotgun", 2,
			"Pistol", 1.5,
			"Pistol2", 1.5,
			"Pistol3", 0.5,
			"Revolver", 1,
			"Revolver_Long", 0.5,
			"GunPowder", 3,
			"ShotgunShellsBox", 3,
			"223Box", 3,
			"308Box", 3,
			"Bullets9mmBox", 3,
			"ShotgunShellsBox", 3,
			"Bullets38Box", 3,
			"Bullets44Box", 3,
			"Bullets45Box", 3,
			"Bag_NormalHikingBag", 1,
			"HuntingKnife", 3,
			"Radio.WalkieTalkie4",10,
			"Radio.WalkieTalkie5",1,
			"Radio.HamRadio1",5,
			"Radio.HamRadio2",1,
		},
	},

	metal_shelves =
	{
		rolls = 4,
		items = {
			"9mmClip", 1.5,
			"45Clip", 1.5,
			"44Clip", 1.5,
			"308Clip", 1.5,
			"Nightstick", 4,
			"Shotgun", 3,
			"DoubleBarrelShotgun", 2,
			"Bullets9mmBox", 3,
			"GunPowder", 2,
			"ShotgunShellsBox", 3,
			"Bullets38Box", 3,
			"Bullets44Box", 3,
			"Bullets45Box", 3,
			"223Box", 3,
			"308Box", 3,
			"Pistol", 1.5,
			"Pistol2", 1.5,
			"Pistol3", 0.5,
			"Revolver", 1,
			"Revolver_Long", 0.5,
			"Radio.WalkieTalkie4",10,
			"Radio.WalkieTalkie5",2,
			"Radio.HamRadio1",5,
			"Radio.HamRadio2",2,
		}
	},

	crate =
	{
		rolls = 4,
		items = {
			"9mmClip", 1.5,
			"45Clip", 1.5,
			"44Clip", 1.5,
			"308Clip", 1.5,
			"Nightstick", 4,
			"Shotgun", 3,
			"DoubleBarrelShotgun", 2,
			"Bullets9mmBox", 3,
			"GunPowder", 2,
			"ShotgunShellsBox", 3,
			"Bullets38Box", 3,
			"Bullets44Box", 3,
			"Bullets45Box", 3,
			"223Box", 3,
			"308Box", 3,
			"Pistol", 1.5,
			"Pistol2", 1.5,
			"Pistol3", 0.5,
			"Revolver", 1,
			"Revolver_Long", 0.5,
			"Radio.WalkieTalkie4",10,
			"Radio.WalkieTalkie5",2,
			"Radio.HamRadio1",5,
			"Radio.HamRadio2",2,
		}
	},
};

RGunstoreLootInsertion = {

};
local function RGpostDistributionMerge()
	if AdvFishing then
		RemoveItemFromDistribution(SuburbsDistributions, "FishingTackle");
		RemoveItemFromDistribution(SuburbsDistributions, "FishingTackle2");

		RemoveItemFromDistribution(ProceduralDistributions, "FishingTackle");
		RemoveItemFromDistribution(ProceduralDistributions, "FishingTackle2");
	end
end

Events.OnPostDistributionMerge.Add(RGpostDistributionMerge);