require "Foraging/forageDefinitions"
require "Foraging/ForageDefLGR"

if forageCategories.Metals then

	forageDefs.EngineParts = {
		type = "Base.EngineParts",
		minCount = 1,
		maxCount = 5,
		skill = 9,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 10,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
			TownZone    = 5,
			TrailerPark = 5,
			Nav        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}
	
	forageDefs.SuspensionParts = {
		type = "Base.SuspensionParts",
		minCount = 1,
		maxCount = 1,
		skill = 8,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 10,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
			TownZone    = 5,
			TrailerPark = 5,
			Nav        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.BrakesParts = {
		type = "Base.BrakesParts",
		minCount = 1,
		maxCount = 1,
		skill = 7,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 10,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
			TownZone    = 5,
			TrailerPark = 5,
			Nav        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.TireRubber = {	
		type       = "Base.TireRubber",
		minCount   = 1,
		maxCount   = 2,
		skill      = 4,
		perks      = { "PlantScavenging" },
		chance     = 50,
		xp         = 15,
		categories = { "Junk" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
			TownZone    = 5,
			TrailerPark = 5,
			Nav        = 5,
        },
		months     = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		spawnFunc  = nil,
	}

	forageDefs.SmallGlassPanel = {	
		type       = "Base.SmallGlassPanel",
		minCount   = 1,
		maxCount   = 1,
		skill      = 5,
		perks      = { "PlantScavenging" },
		chance     = 25,
		xp         = 15,
		categories = { "Junk" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
			TownZone    = 5,
			TrailerPark = 5,
			Nav        = 5,
        },
		months     = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		spawnFunc  = nil,
	}	

	forageDefs.BigGlassPanel = {	
		type       = "Base.BigGlassPanel",
		minCount   = 1,
		maxCount   = 1,
		skill      = 6,
		perks      = { "PlantScavenging" },
		chance     = 10,
		xp         = 15,
		categories = { "Junk" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
			TownZone    = 5,
			TrailerPark = 5,
			Nav        = 5,
        },
		months     = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		spawnFunc  = nil,
	}	

end