require "Foraging/forageDefinitions"
require "Foraging/ForageDefLGR"

if forageCategories.Metals then
	if forageSkills then
		forageSkills.ammospecialist = {
			name                    = "ammospecialist",
			type                    = "occupation",
			visionBonus             = 0,
			weatherEffect           = 0,
			darknessEffect          = 0,
			specialisations         = {
				["Animals"]             = 5,
				["Ammunition"]          = 30,
				["Metals"]              = 30,
				["Trash"]               = 10,
				["Junk"]                = 10,
			},
		}
	end
	forageDefs.Lead = {
		type = "AmmoMaker.Lead",
		minCount = 1,
		maxCount = 5,
		skill = 1,
		perks       = { "PlantScavenging" },
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Casq9mm = {
		type = "AmmoMaker.Casq9mm",
		minCount = 1,
		maxCount = 3,
		skill = 2,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Casq223 = {
		type = "AmmoMaker.Casq223",
		minCount = 1,
		maxCount = 3,
		skill = 3,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Casq308 = {
		type = "AmmoMaker.Casq308",
		minCount = 1,
		maxCount = 3,
		skill = 4,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.CasqShotgun = {
		type = "AmmoMaker.CasqShotgun",
		minCount = 1,
		maxCount = 3,
		skill = 5,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Casq762x39mm = {
		type = "AmmoMaker.Casq762x39mm",
		minCount = 1,
		maxCount = 3,
		skill = 10,
		perks       = { "PlantScavenging" },
		chance      = 5,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Lead9mm = {
		type = "AmmoMaker.Lead9mm",
		minCount = 1,
		maxCount = 1,
		skill = 6,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Lead38 = {
		type = "AmmoMaker.Lead38",
		minCount = 1,
		maxCount = 1,
		skill = 7,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.LeadPellets = {
		type = "AmmoMaker.LeadPellets",
		minCount = 1,
		maxCount = 1,
		skill = 7,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Lead223 = {
		type = "AmmoMaker.Lead223",
		minCount = 1,
		maxCount = 1,
		skill = 8,
		perks       = { "PlantScavenging" },
		chance      = 2,
		xp          = 10,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Lead44 = {
		type = "AmmoMaker.Lead44",
		minCount = 1,
		maxCount = 1,
		skill = 9,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Lead308 = {
		type = "AmmoMaker.Lead308",
		minCount = 1,
		maxCount = 1,
		skill = 9,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Lead556x45mm = {
		type = "AmmoMaker.Lead556x45mm",
		minCount = 1,
		maxCount = 1,
		skill = 10,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Lead45 = {
		type = "AmmoMaker.Lead45",
		minCount = 1,
		maxCount = 1,
		skill = 10,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.Lead762x39mm = {
		type = "AmmoMaker.Lead762x39mm",
		minCount = 1,
		maxCount = 3,
		skill = 10,
		perks       = { "PlantScavenging" },
		chance      = 5,
		xp          = 2,
		rainChance  = 0,
		snowChance  = -10,
		itemHands    = { "MetalDetector" },
		recipes     = {},
		categories  = { "Metals" },
        zones = {
            Forest      = 10,
            DeepForest  = 15,
            Vegitation  = 5,
            FarmLand    = 5,
            Farm        = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
	}

	forageDefs.ToolPart1 = {
		type = "AmmoMaker.ToolPart1",
		skill = 4,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 5,
		recipes     = {},
		categories  = { "Metals", "Junk" },
        zones = {
			Forest      = 5,
			DeepForest  = 5,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
			TrailerPark = 5,
			TownZone    = 5,
			Nav         = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
		forceOutside = false,
        canBeAboveFloor = true,
	}
	forageDefs.ToolPart2 = {
		type = "AmmoMaker.ToolPart2",
		skill = 4,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 5,
		recipes     = {},
		categories  = { "Metals", "Junk" },
        zones = {
			Forest      = 5,
			DeepForest  = 5,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
			TrailerPark = 5,
			TownZone    = 5,
			Nav         = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
		forceOutside = false,
        canBeAboveFloor = true,
	}
	forageDefs.ToolPart3 = {
		type = "AmmoMaker.ToolPart3",
		skill = 4,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 5,
		recipes     = {},
		categories  = { "Metals", "Junk" },
        zones = {
			Forest      = 5,
			DeepForest  = 5,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
			TrailerPark = 5,
			TownZone    = 5,
			Nav         = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
		forceOutside = false,
        canBeAboveFloor = true,
	}
	forageDefs.ToolPart4 = {
		type = "AmmoMaker.ToolPart4",
		skill = 4,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 5,
		recipes     = {},
		categories  = { "Metals", "Junk" },
        zones = {
			Forest      = 5,
			DeepForest  = 5,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
			TrailerPark = 5,
			TownZone    = 5,
			Nav         = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
		forceOutside = false,
        canBeAboveFloor = true,
	}
	forageDefs.ToolPart5 = {
		type = "AmmoMaker.ToolPart5",
		skill = 4,
		perks       = { "PlantScavenging" },
		chance      = 10,
		xp          = 5,
		recipes     = {},
		categories  = { "Metals", "Junk" },
        zones = {
			Forest      = 5,
			DeepForest  = 5,
			Vegitation  = 5,
			FarmLand    = 5,
			Farm        = 5,
			TrailerPark = 5,
			TownZone    = 5,
			Nav         = 5,
        },
		months      = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
		bonusMonths = {},
		malusMonths = {},
		spawnFunc	= nil,
		forceOutside = false,
        canBeAboveFloor = true,
	}
end

local function generateAMCustomDefs()
	local junkItems = {
		rare = {
			chance = 15,
			xp = 10,
			items = {
				AmmoMagazine1         = "AmmoMaker.AmmoMagazine1",
				AmmoMagazine2         = "AmmoMaker.AmmoMagazine2",
				AmmoMagazine3         = "AmmoMaker.AmmoMagazine3",
				AmmoMagazine6         = "AmmoMaker.AmmoMagazine6",
				AmmoMagazine7         = "AmmoMaker.AmmoMagazine7",
				AmmoMagazine8         = "AmmoMaker.AmmoMagazine8",
				AmmoMagazine9         = "AmmoMaker.AmmoMagazine9",
				AmmoMagazine10        = "AmmoMaker.AmmoMagazine10",
				AmmoMagazine11        = "AmmoMaker.AmmoMagazine11",
				AmmoMagazine12        = "AmmoMaker.AmmoMagazine12",
				AmmoMagazine13        = "AmmoMaker.AmmoMagazine13",
				AmmoMagazine14        = "AmmoMaker.AmmoMagazine14",
				WeaponsMagazine4      = "AmmoMaker.WeaponsMagazine4",
			},
		},
		epic = {
			chance = 5,
			xp = 20,
			items = {				
                ["ReloadingToolBroken"]    = "AmmoMaker.ReloadingToolBroken",
                ["ReloadingTool"]          = "AmmoMaker.ReloadingTool",
                ["AmmoPliers"]             = "AmmoMaker.AmmoPliers",
                ["9mmMold"]                = "AmmoMaker.9mmMold",
				["223Mold"]                = "AmmoMaker.223Mold",
				["308Mold"]                = "AmmoMaker.308Mold",
				["PelletsMold"]            = "AmmoMaker.PelletsMold",
				["556Mold"]                = "AmmoMaker.556Mold",
				["38Mold"]                 = "AmmoMaker.38Mold",
				["44Mold"]                 = "AmmoMaker.44Mold",
				["45Mold"]                 = "AmmoMaker.45Mold",
				["762Mold"]                = "AmmoMaker.762Mold",
			},
		},
        legendary = {
            chance = 1,
            xp = 30,
            items = {
                SilencerAK        = "AmmoMaker.SilencerAK",
                AKHG              = "AmmoMaker.AKHG",
                AKRecoilPad       = "AmmoMaker.AKRecoilPad",
                AKTacticalLight   = "AmmoMaker.AKTacticalLight",
                AkIronSight2      = "AmmoMaker.AkIronSight2",
                AK47x4Scope       = "AmmoMaker.AK47x4Scope",
                AK47MilitaryScope = "AmmoMaker.AK47MilitaryScope",
            },
        },
	};
    for _, spawnTable in pairs(junkItems) do
        for itemName, itemFullName in pairs(spawnTable.items) do
            forageDefs[itemName] = {
                type = itemFullName,
                skill = 4,
                xp = spawnTable.xp,
                categories = { "Junk" },
                zones = {
                    Forest      = spawnTable.chance,
                    DeepForest  = spawnTable.chance,
                    Vegitation  = spawnTable.chance,
                    FarmLand    = spawnTable.chance,
                    Farm        = spawnTable.chance,
                    TrailerPark = spawnTable.chance,
                    TownZone    = spawnTable.chance,
                    Nav         = spawnTable.chance,
                },
                spawnFuncs = nil,
                forceOutside = false,
                canBeAboveFloor = true,
            };
        end;
    end;
end

generateAMCustomDefs();

	-- table.insert(scavenges.Metals, Lead45);
