require 'Items/SuburbsDistributions'
require 'Items/Distributions'

table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagSprint");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagLightFoot");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagNimble");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagSneaking");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagCarpentry");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagCooking");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagFarming");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagFirstAid");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagElectricity");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagMetal");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagFirearm");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagReloading");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagFishing");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagTrapping");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagForaging");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagMechanics");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagAxe");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagBlade");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagBlade");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagBlunt");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagBlunt");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagSpear");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagMaintenance");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagTailor");
table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);

-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagSprint");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagLightFoot");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagNimble");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagSneaking");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagCarpentry");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagCooking");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagFarming");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagFirstAid");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagElectricity");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagMetal");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagFirearm");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagReloading");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagFishing");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagTrapping");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagForaging");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagMechanics");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagAxe");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagBlade");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagBlade");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagBlunt");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagBlunt");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagSpear");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagMaintenance");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, "SkillMag.SkillMagTailor");
-- table.insert(SuburbsDistributions["cornerstore"]["shelvesmag"].items, 0.075);

-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagSprint");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagLightFoot");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagNimble");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagSneaking");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagCarpentry");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagCooking");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagFarming");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagFirstAid");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagElectricity");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagMetal");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagFirearm");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagReloading");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagFishing");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagTrapping");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagForaging");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagMechanics");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagAxe");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagBlade");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagBlade");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagBlunt");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagBlunt");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagSpear");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagMaintenance");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, "SkillMag.SkillMagTailor");
-- table.insert(SuburbsDistributions["zippeestore"]["shelvesmag"].items, 0.1);

-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagSprint");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagLightFoot");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagNimble");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagSneaking");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagCarpentry");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagCooking");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagFarming");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagFirstAid");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagElectricity");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagMetal");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagFirearm");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagReloading");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.075);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagFishing");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagTrapping");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagForaging");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagMechanics");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagAxe");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagBlade");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagBlade");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagBlunt");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagBlunt");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagSpear");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagMaintenance");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, "SkillMag.SkillMagTailor");
-- table.insert(SuburbsDistributions["fossoil"]["shelvesmag"].items, 0.3);

table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagSprint");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagLightFoot");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagNimble");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagSneaking");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagCarpentry");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagCooking");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagFarming");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagFirstAid");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagElectricity");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagMetal");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagFirearm");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagReloading");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagFishing");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagTrapping");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagForaging");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagMechanics");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagAxe");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagBlade");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagBlade");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagBlunt");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagBlunt");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagSpear");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagMaintenance");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagTailor");
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);

-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagSprint");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagLightFoot");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagNimble");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagSneaking");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagCarpentry");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagCooking");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagFarming");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagFirstAid");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagElectricity");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagMetal");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagFirearm");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagReloading");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagFishing");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagTrapping");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagForaging");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagMechanics");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagAxe");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagBlade");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagBlade");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagBlunt");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagBlunt");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagSpear");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagMaintenance");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, "SkillMag.SkillMagTailor");
-- table.insert(SuburbsDistributions["bedroom"]["sidetable"].items, 0.05);

table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagSprint");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagLightFoot");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagNimble");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagSneaking");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagCarpentry");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagCooking");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagFarming");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagFirstAid");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagElectricity");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagMetal");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagFirearm");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagReloading");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagFishing");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagTrapping");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagForaging");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagMechanics");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagAxe");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagBlade");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagBlade");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagBlunt");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagBlunt");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagSpear");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagMaintenance");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagTailor");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);

table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagPackage");
table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.1);

local function skillsmagmergeDistributions()
	local AmmoMaker = nil;
	if ISAMReloadingMenu then
		AmmoMaker = true
	end
	if AmmoMaker ~= nil then
		table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagAmmoReloading");
		table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
		table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagAmmoReloading");
		table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);	
		table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagAmmoReloading");
		table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
	
	end
	local LGR = nil;
	if LeGourmet then
		LGR = true
	end
	if LGR ~= nil then
		table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "SkillMag.SkillMagHunting");
		table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 0.075);
		table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "SkillMag.SkillMagHunting");
		table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.05);	
		table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, "SkillMag.SkillMagHunting");
		table.insert(ProceduralDistributions["list"]["PostOfficeMagazines"].items, 0.05);
	end
	local LCSkillMagDist = nil;
	if LCLootInsertion then
		LCSkillMagDist = true;
	end
	if LCSkillMagDist ~= nil then
	    print ("Items de SkillsMag Mod agregados a Lobii City");
        table.insert(SuburbsDistributions["LCpharmacy"]["shelvesmag"].items, "SkillMag.SkillMagFirstAid");
		table.insert(SuburbsDistributions["LCpharmacy"]["shelvesmag"].items, 3);

        table.insert(SuburbsDistributions["cerrajero"]["counter"].items, "SkillMag.SkillMagNimble");
		table.insert(SuburbsDistributions["cerrajero"]["counter"].items, 3);

        table.insert(SuburbsDistributions["paintsore"]["counter"].items, "SkillMag.SkillMagCarpentry");
		table.insert(SuburbsDistributions["paintsore"]["counter"].items, 3);

        table.insert(SuburbsDistributions["fishingbook"]["shelvesmag"].items, "SkillMag.SkillMagFishing");
		table.insert(SuburbsDistributions["fishingbook"]["shelvesmag"].items, 3);
        table.insert(SuburbsDistributions["fishingbook"]["shelvesmag"].items, "SkillMag.SkillMagTrapping");
		table.insert(SuburbsDistributions["fishingbook"]["shelvesmag"].items, 3);
        table.insert(SuburbsDistributions["fishingbook"]["shelvesmag"].items, "SkillMag.SkillMagForaging");
		table.insert(SuburbsDistributions["fishingbook"]["shelvesmag"].items, 3);

        table.insert(SuburbsDistributions["farmstore"]["shelvesmag"].items, "SkillMag.SkillMagFarming");
		table.insert(SuburbsDistributions["farmstore"]["shelvesmag"].items, 3);
	end
end

Events.OnDistributionMerge.Add(skillsmagmergeDistributions);